### ISSUE TITLE
Glue SR3 mirror

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#10]
### TODO
- [X] glue 1st wire breakers
- [X] glue 2nd wire breakers 
- [X] glue magnets. 
- [X] check if it is glued properly
### Ship to the Toyama-Univ.
- [x] since the First Contact (FC) has been applied at the one-opposite side, this is to be shipped to Toyama-Univ.

**Comment by YoshinoriFujii** [comment]
The FC issue went away. The SR3 mirror has come bask to the tunnel.[k-log#4629](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4629 "k-log#4629")

**Comment by YoshinoriFujii** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes  
> Mark glued prisms and magnet/standoff assemblies on the SR3. The SR3 needed to be raised in the box by 0.7 mm to make the prisms go on at the right height, which was done using M4 washers under the PEEK feet.
> Mark glued ferromagnetic disks on the last 5 IM flags. This completes 2 sets, for SR3 and SRM.

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4752
properly attached on the optic on 2018-April-20.
