### ISSUE TITLE
TODO in the week of 2018-4-9

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#12]
### Work inside the tunnel
- [x] Finish BFs tasks (cabling +calibration) #2 (#3)
- [x] Finish SFs tasks (cabling +calibration) #5 , #6 

- [ ] Build ~2xIM~, ~2x~RM #8 

- [x] Gluing on SR3 mirror

### Work outside the tunnel
- [x] add parameters into the MEDM

### Collect information (by YF)

**Comment by YoshinoriFujii** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes  
> Enzo and Kozu-kun finished preparing and calibrating the SF and BF for SR3 and almost entirely finished with those for SRM.

**Comment by YoshinoriFujii** [comment]
http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeB/Minutes
> Report for week of 4/9
> We packed away the SRM SF and BF.
> After several failed attempts with one secondary prism, Mark finished the SR3 prism/magnet gluing.
> Tanioka-kun built two IRMs (less OSEMs).
> Enzo built an RM.
> Kozu-kun and Enzo calibrated one set of 6 IM OSEMs for SR3. (6 OSEMs for SRM remain to be done.)
> Hirata-san aligned the assembly frame, installed the interface bars and IM ring, and install

ed the IM.

**Comment by YoshinoriFujii** [comment]
RM issue (#16) is taken over to the #19 .
