### ISSUE TITLE
GAS-LVDT noise-level measurement

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#18]
### TODO
measure the noise level of the GAS-LVDTs with the keystone locked.

### checklist
- [ ] BF-No1 (for SRM)
- [ ] BF-No7 (for SR3)
- [ ] SF-B2-5 (for SRM)
- [ ] BF-B2-6 (for SR3)

**References**
BF-No1 #2  
BF-No7 #3 
SF-B2-5 #5 
BF-B2-6 #6

**Comment by MiyoKouseki** [comment]
Can I close this issue?
