### ISSUE TITLE
BF-No1 preparation

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#2]
# Purpose
Characterize the BF for SR3 or SRM.
HERE, information of **BF-No1** is described.

# TODO
- [X] Compression tuning & resonant frequency measurement
- [X] keystone tilt check
- [X] Cabling (~LDVT~/***pico***/~stepper~)
- [X] Check the yoke position
- [x] Calibration 
-   ~~blade assembly~~
- [x] Yoke position check
- [x] Fishing rod range check

**Comment by YoshinoriFujii** [comment]
- The optimal load, optimal resonant frequency and optimal height are 52.15 kg, 0.37 Hz and 64.7 mm respectively.
- The ballast masses might be re-machined since these masses were designed for BF whose optimal load is about 52kg.

**Comment by YoshinoriFujii** [comment]
cables for picomotor should be removed once and then is to be re-installed after IM installation.

**Comment by YoshinoriFujii** [comment]
Measured data is here: [BF-No1.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879511/BF-No1.txt)

**Comment by YoshinoriFujii** [comment]
[klog#4721](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4721 "klog#4721")
> For SRM_BF (BF_No1):
> 
> We prepared the load of **52.176[kg]** to set the keystone at nominal position (65.5 [mm]).
> The fishing rod height range is from 19.8 [mm] to 50.7 [mm].
> The keystone adjustment range (using the fishing rod) is from **62.5 [mm] to 68.3 [mm].** 
> So the keystone can be moved around +/- 2.8 [mm] from the nominal position. See figure 2.
