### ISSUE TITLE
SF-B2-5 preparation

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#5]
# Puarpose
Characterize the BF for SR3 or SRM.
HERE, information of **SF-B2-5** is described.

# TODO
- ~~blade assembly~~
- [x] Compression tuning & resonant frequency measurement [k-log#4580](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4580 "k-log#4580")
- [X] keystone tilt check
- [x] Cabling (LDVT/stepper)
- [X] Check the yoke position
- [x] LVDT calibration
- [x] Yoke position check
- [x] Fishing rod range check

**Comment by YoshinoriFujii** [comment]
Concerning Yoke position, which should be correct?:
3.5 mm or 6 mm,
for the height of the coil-bobbin from the base plate. 
For BF, this should be 3.5 mm. How about SF?

**Comment by YoshinoriFujii** [comment]
For SF, it should be 6mm.

**Comment by YoshinoriFujii** [comment]
[2018-3-28-SF-B2-5_summary.pdf](https://github.com/gw-vis/SR_installation_preparation/files/1879616/2018-3-28-SF-B2-5_summary.pdf)

[2018-3-28-SF-B2-5_w-cap.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879621/2018-3-28-SF-B2-5_w-cap.txt)
[2018-3-28-SF-B2-5_wo-cap.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879622/2018-3-28-SF-B2-5_wo-cap.txt)

**Comment by YoshinoriFujii** [comment]
[klog#4688](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4688 "klog#4688")

> For SRM_SF (SF-B2-5):
> 
> We adjusted the yoke position to 6[mm]
> LVDT reading with the keystone at the highest position: 32767[cnt] (Keystone at 76.5[mm])
> LVDT reading with the keystone at the lowest position: -20920[cnt] (Keystone at 56.5[mm])
> Calibration factor: 1/(7092.12) [cnt/mm]=0.141 [um/cnt]
> Offset: 4005 [cnt]
>  
> Note: Both filters exhibit an hysteresis in this process, so we may need to re visit the offset number later.
> Later on we need to introduce this calibration factors into the digital system for the SRM suspension and take a Snapshoot.
> Images attached to this report

**Comment by YoshinoriFujii** [comment]
[klog#4721](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4688 "klog#4721")

> For SRM_SF (SF-B2-5):
> 
> We prepared the load of 166.301 [kg] to set the keystone at nominal position (65.5 [mm]).
> The fishing rod height range is from 19.8 [mm] to 54.4 [mm].
> The keystone adjustment range (using the fishing rod) is from 63.8 [mm] to 66.9 [mm]. 
> So the keystone can be moved around +/- 1.4 [mm] from the nominal position. See figure 3.
