### ISSUE TITLE
SF-B2-6 preparation

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#6]
# Puarpose
Characterize the BF for SR3 or SRM.
HERE, information of **SF-B2-6** is described.

# TODO
- ~~blade assembly~~
- [x] Compression tuning & resonant frequency measurement
- [X] keystone tilt check
- [X] Cabling (~LDVT~/~stepper~)
- [X] Check the yoke position
- [x] LVDT calibration
- [x] Yoke position check
- [x] Fishing rod range check

**Comment by YoshinoriFujii** [comment]
[k-log#4622](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4622 "k-log#4622")

**Comment by YoshinoriFujii** [comment]
| optimal frequency | optimal load | optimal height of the keystone |
| :---: | :---: | :---: |
| 0.32 Hz |166.40 kg | 142.1 mm|

**Comment by YoshinoriFujii** [comment]
[SF-B2-6_w-cap_loosen.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879626/SF-B2-6_w-cap_loosen.txt)
[SF-B2-6_w-cap_tighten.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879627/SF-B2-6_w-cap_tighten.txt)
[SF-B2-6_wo-cap.txt](https://github.com/gw-vis/SR_installation_preparation/files/1879628/SF-B2-6_wo-cap.txt)
[SF-B2-6-summary.pdf](https://github.com/gw-vis/SR_installation_preparation/files/1879634/SF-B2-6-summary.pdf)

**Comment by YoshinoriFujii** [comment]
calibration: [k-log#4656](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4656 "k-log#4656")

**Comment by YoshinoriFujii** [comment]
http://klog.icrr.u-tokyo.ac.jp/osl/?r=4720

> This is a pendant report from last week. With Kozu-kun:
> 
> We checked the performance of the fishing rod (FR) moving the stepper motor of SF for SR3 suspension.
> 
> The FR height is measured from the metal base plate of the stepper motor to the top of the PEEK plate. See picture 1.
> 
> For SR3_SF (SF-B2-6):
> 
> We prepared the load of 166.409[kg] to set the keystone at nominal position (65.5 [mm]).
> The fishing rod height range is from 19.6 [mm] to 54.7 [mm].
> The keystone adjustment range (using the fishing rod) is from 63.5 [mm] to 67.5 [mm]. 
> So the keystone can be moved around +/- 2 [mm] from the nominal position (65.5 [mm]). See figure 2. 
> 
> Note: The filters were without the cap when the data was taken.

**Comment by YoshinoriFujii** [comment]
**TODO**
- [ ] install Cu ring on the cap
