### ISSUE TITLE
TODO in the week of 2018-4-2

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/SR_installation_preparation#7]
#### group-1
- [ ] Finish BFs tasks (cabling +calibration) 
- [ ] Finish SFs tasks (cabling +calibration)  

#### group-2
- [ ] Build 2xIM, 2xIRM

#### group-3
- [ ] Add cable clamps to bases.
- [ ] Add cable clamps and Cu segments to caps (only if they fit well).
- [ ] Glue SR3 mirror?

### Work outside the tunnel
- [ ] modify MEDM for SR3

**Comment by YoshinoriFujii** [comment]
The information of GAS filters for SR3 and SRM

| GAS name | optimal load | optimal frequency | optimal height of the keystone | for which? | Note |
| :---: | :---: | :---: | :---: | :---: | :---: |
| SF-B2-5 | 0.34 Hz |166.14 kg | 68.1 mm |  |  |
| SF-B2-6 | 0.32 Hz |166.40 kg | 67.8 mm |  |  |
|  |  |  |  |  |  |
| BF-No1 | 0.37 Hz | 52.15 kg | 64.7 mm |  |  |
| BF-No7 |  | 53.17 kg |  |  | Kozu-kun will update soon. |

**Comment by Satoshi-Tanioka** [comment]
According to Mark, the height of prism is not appropriate now (April 11th).

**Comment by YoshinoriFujii** [comment]
[k-log#4747](http://klog.icrr.u-tokyo.ac.jp/osl/?r=4747 "k-log#4747")

> The keystone height was measured with a ruler (the same way as for the LVDT calibration).
> 
> About to the linear range of the filters, and summarizing what we did:
> 
> For SR3:
> 
> SR3-BF Linear range: 64[mm] to 66.5[mm].
> The FR can move the Keystone down from nominal position to 64.2[mm] and can move it up to 66.5[mm].
> SR3-SF Linear range: 63.5[mm] to 68[mm].
> The FR can move the Keystone down from nominal position to 63.5[mm] and can move it up to 67.5[mm].
>  
> 
> For SRM:
> 
> SRM-BF Linear range: 62.5[mm] to 69.5[mm].
> The FR can move the Keystone down from nominal position to 62.5[mm] and can move it up to 68.4[mm].
> SRM-SF Linear range: 62[mm] to 69[mm].
> The FR can move the Keystone down from nominal position to 63.8[mm] and can move it up to 66.9[mm].
>  
> 
> So the FR can move the keystone within the linear range of the LVDT for the corresponding GAS filter.
